df_install_binary() {
  local binDir

  binDir="${HOME}/.local/bin"

  local name=${1}
  local url=${2}

  local filePath="${binDir}/${name}"

  rm -rf "${filePath}"
  curl -L "${url}" -o "${filePath}"

  chmod +x ${filePath}
}

# generated by chatgpt
df_install_kill_ports() {
  local binDir="${HOME}/.local/bin"
  local scriptFile="${binDir}/kill-ports"

  if [ ! -d "${binDir}" ]; then
    mkdir -p "${binDir}"
  fi

  cat << EOF > "${scriptFile}"
#!/bin/bash

function kill-ports() {
  for port in "\$@"; do
    pid="\$(lsof -t -i :"\$port")"
    if [ -n "\$pid" ]; then
      echo "Killing process listening on port \$port (PID \$pid)..."
      kill "\$pid"
    else
      echo "No process listening on port \$port"
    fi
  done
}

kill-ports "\$@"
EOF

  chmod +x "${scriptFile}"
  echo "kill-ports installed to ${binDir}"
}

df_install_binaries() {
  df_install_binary "diff-so-fancy" "https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy"
  df_install_kill_ports
}
