DF_INSTALL_BINARIES_LOCAL_BIN_DIR="${HOME}/.local/bin"

df_install_binary() {
  local name=${1}
  local url=${2}

  local filePath="${DF_INSTALL_BINARIES_LOCAL_BIN_DIR}/${name}"

  rm -rf "${filePath}"
  curl -L "${url}" -o "${filePath}"

  chmod +x ${filePath}
}

# generated by chatgpt
df_install_kill_ports() {
  local scriptFile="${DF_INSTALL_BINARIES_LOCAL_BIN_DIR}/kill-ports"

  cat << EOF > "${scriptFile}"
#!/bin/bash

function kill-ports() {
  for port in "\$@"; do
    pid="\$(lsof -t -i :"\$port")"
    if [ -n "\$pid" ]; then
      echo "Killing process listening on port \$port (PID \$pid)..."
      kill "\$pid"
    else
      echo "No process listening on port \$port"
    fi
  done
}

kill-ports "\$@"
EOF

  chmod +x "${scriptFile}"
  echo "kill-ports installed to ${DF_INSTALL_BINARIES_LOCAL_BIN_DIR}"
}

df_install_wsl_ssh_agent_relay() {
  df_install_binary "wsl-ssh-agent-relay" "https://raw.githubusercontent.com/rupor-github/wsl-ssh-agent/master/docs/wsl-ssh-agent-relay"

  df_install_bashrc_append '${HOME}/.local/bin/wsl-ssh-agent-relay start'
  df_install_bashrc_append 'export SSH_AUTH_SOCK=${HOME}/.ssh/wsl-ssh-agent.sock'
}

df_install_binaries() {
  local scriptFile="${DF_INSTALL_BINARIES_LOCAL_BIN_DIR}/kill-ports"

  if [ ! -d "${DF_INSTALL_BINARIES_LOCAL_BIN_DIR}" ]; then
    mkdir -p "${DF_INSTALL_BINARIES_LOCAL_BIN_DIR}"
  fi

  df_install_binary "diff-so-fancy" "https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy"
  df_install_kill_ports

  if [ "${DF_PLATFORM}" == "WSL" ]; then
    df_install_wsl_ssh_agent_relay
  fi
}
